### ISSUE TITLE
Rule check warning on Polygon Circle in Package and Assembly outline

### ISSUE THREAD

**Issue by trembel** [horizon-eda/horizon#489] opened 2020-08-05 22:12 UTC
If I draw a Polygon Circle as the only element in the "Top Package" or "Top Assembly" layer, the rule checker warns with "Use polygons to draw outlines on package layers"

**Comment by carrotIndustries** [comment] 2020-08-06 17:31
I can't reproduce this, can you share the package.json where this happens?

**Comment by trembel** [comment] 2020-08-06 17:50
This is the package:

[package.json.log](https://github.com/horizon-eda/horizon/files/5036949/package.json.log)
FIY: I changed the name to `*.log`, because it is not possible to add a `*.json` to a comment.

Maybe it is connected to another bug. I experienced, that after duplicating a part (from an included pool) I'm not able to change the courtyard. See attached GIF
![courtyard](https://user-images.githubusercontent.com/28383252/89564956-1750a100-d81e-11ea-96cd-132f7eed7948.gif)

**Comment by trembel** [comment] 2020-08-06 17:55
The courtyard is no error. It is a polygon program. After deleting, it is possible to create a new one

**Comment by carrotIndustries** [comment] 2020-08-06 23:14
> This is the package:

Well, the thing sticking out on the top left is a line.

Since none of this was really a bug, I'm closing this issue. If there's any more need for discussion, start a topic on discourse: https://horizon-eda.discourse.group/

**Closed by carrotIndustries** 2020-08-06 23:14 UTC
