### ISSUE TITLE
Usability: make vias selectable in layer mode "Shadodw other"

### ISSUE THREAD

**Issue by anuejn** [horizon-eda/horizon#503] opened 2020-08-23 17:07 UTC
To me, one of the most workflow breaking things is, that vias are not selectable in the "Shadow Other" mode.
It makes me switch always back and forth between "As is" and "Shadow Other" which is annoying.

**Comment by carrotIndustries** [comment] 2020-08-24 21:40
Duplicate of #447

**Closed by carrotIndustries** 2020-08-24 21:40 UTC

**Comment by anuejn** [comment] 2020-08-25 11:40
ah sorry for the noise
