### ISSUE TITLE
Rule to prevent via in pad

### ISSUE THREAD

**Issue by rroohhh** [horizon-eda/horizon#419] opened 2020-06-13 18:44 UTC
Currently there is no way (atleast I did not find one) to specify the minimum clearance between a via and a pad of the same net.

**Comment by carrotIndustries** [comment] 2020-06-14 17:13
Should this clearance be based on via hole to pad distance or via pad to pad distance?

**Comment by rroohhh** [comment] 2020-06-14 23:02
Via pad to pad distance seems better to me.

**Comment by carrotIndustries** [comment] 2020-06-14 23:20
Okay, seems reasonable. The more general solution here is same net clearance. However, there's an issue with that:

For DRC, the entire board gets dumped into a set of polygons (patches) grouped by type (via, track, etc), layer and net. This means that we can't do same-net clearance between to objects of the same type as they could have been merged into one patch if they overlap.

Can you think of any other sensible type pairs other than pad-via for same net clearance?

**Comment by rroohhh** [comment] 2020-06-15 00:57
Some I think could be useful:
- via to via clearance
- via to pth clearance
- pad to pth clearance

**Comment by carrotIndustries** [comment] 2020-06-28 23:01
Have a look at the commit mentioned above. If it works as intended, I'll merge it into master.

**Comment by rroohhh** [comment] 2020-06-29 18:51
If I understand the previous commit correctly, this only applies those rules during DRC, and not for example for the router, right?

I think having the router abide by these rules would be very useful.

**Comment by carrotIndustries** [comment] 2020-06-29 18:54
> If I understand the previous commit correctly, this only applies those rules during DRC, and not for example for the router, right?

Yes, as far as I am aware the kicad router doesn't support same net clearance.

**Comment by rroohhh** [comment] 2020-06-29 18:57
I see. 

I will play around with it a bit more.

**Closed** 2020-08-29 11:27 UTC
